swagger: "2.0"
info:
  version: 0.0.1
  title: Trial System API
host: localhost
basePath: /trials/api/v1
schemes:
  - https
security:
  - Bearer: []
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
paths:
  "/trials/{trialId}/subscriptions":
    parameters:
      - $ref: "#/parameters/pathTrialId"
    get:
      operationId: getSubscription
      summary: Get subscription detail
      description: >-
        Returns the details about the subscription of the authenticated user for
        the specified trial.
      responses:
        "200":
          $ref: "#/responses/200Subscription"
        "401":
          $ref: "#/responses/401Unauthorized"
        "404":
          $ref: "#/responses/404NotFound"
        "429":
          $ref: "#/responses/429TooManyRequest"
        "500":
          $ref: "#/responses/500Error"
    post:
      operationId: createSubscription
      summary: Create a subscription
      description: >-
        Subscribe the authenticated user to the given trial.
      responses:
        "201":
          $ref: "#/responses/201Subscription"
        "400":
          $ref: "#/responses/400Error"
        "401":
          $ref: "#/responses/401Unauthorized"
        "409":
          $ref: "#/responses/409Conflict"
        "429":
          $ref: "#/responses/429TooManyRequest"
        "500":
          $ref: "#/responses/500Error"

parameters:
  pathTrialId:
    name: trialId
    in: path
    required: true
    type: string
    minLength: 1

definitions:
  ProblemJson:
    $ref: "../node_modules/@pagopa/io-functions-commons/openapi/definitions.yaml#/ProblemJson"
  CreatedAt:
    $ref: "../node_modules/@pagopa/io-functions-commons/openapi/definitions.yaml#/Timestamp"
  SubscriptionState:
    type: string
    description: |-
      - UNSUBSCRIBED: The user is not subscribed to the specified trial and does
          not have any access to the specified trial.
      - SUBSCRIBED: The user is subscribed to the specified trial and does
          not have any access to the specified trial. The system is going to
          activate the user if any slot for the trial is available.
      - ACTIVE: The user has the access to the specified trial.
      - DISABLED: The user does not have the access to the specified trial.
    enum:
      - UNSUBSCRIBED
      - SUBSCRIBED
      - ACTIVE
      - DISABLED
  TrialId:
    type: string
    description: >-
      Unique identifier of the trial.
    minLength: 1
  Subscription:
    type: object
    properties:
      trialId:
        $ref: '#/definitions/TrialId'
      state:
        $ref: '#/definitions/SubscriptionState'
      createdAt:
        $ref: '#/definitions/CreatedAt'

responses:
  200Subscription:
    description: Success.
    schema:
      $ref: "#/definitions/Subscription"
  201Subscription:
    description: Success.
    schema:
      $ref: "#/definitions/Subscription"
  400Error:
    description: Validation error.
    schema:
      $ref: "#/definitions/ProblemJson"
  401Unauthorized:
    description: Authorization error.
  404NotFound:
    description: Resource not found.
  409Conflict:
    description: The resource already exists.
  429TooManyRequest:
    description: Too may requests.
  500Error:
    description: There was an error.
    schema:
      $ref: "#/definitions/ProblemJson"
